In [1]:
import numpy as np
import nltk

"""nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')"""

"nltk.download('wordnet')\nnltk.download('stopwords')\nnltk.download('punkt')"

# Bag of words 

In [2]:
class Category:
    Books = 'Books'
    Clothes = 'Clothes'
    
train_x = ['I love this book','What a great book','This looks great','love the shoes']
train_y = [Category.Books, Category.Books, Category.Clothes, Category.Clothes]

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

#ngram = tamanho das sequencias de tokens a serem consideradas
vectorizer = CountVectorizer(binary=True, ngram_range=(1,1))
train_x_vec = vectorizer.fit_transform(train_x)

print(vectorizer.get_feature_names(),'\n\n',train_x_vec.toarray())

['book', 'great', 'looks', 'love', 'shoes', 'the', 'this', 'what'] 

 [[1 0 0 1 0 0 1 0]
 [1 1 0 0 0 0 0 1]
 [0 1 1 0 0 0 1 0]
 [0 0 0 1 1 1 0 0]]


In [4]:
from sklearn import svm

clf_svm = svm.SVC(kernel='linear')
clf_svm.fit(train_x_vec,train_y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [5]:
#predict
test_x = vectorizer.transform(['love the book'])

clf_svm.predict(test_x)

array(['Books'], dtype='<U7')

# Word Vectors

In [6]:
import spacy
''' en_core_web_sm   -ingles
    pt_core_news_sm  -portuges'''

nlp=spacy.load('en_core_web_sm')

In [7]:
doc = [nlp(text) for text in train_x]

train_x_wv = [x.vector for x in doc]

#print(train_x_wv[0])

In [8]:
clf_wv = svm.SVC(kernel='linear')
clf_wv.fit(train_x_wv,train_y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [9]:
#predict
try_x = ['love to read it']
test_doc = [nlp(text) for text in try_x]
test_x = [x.vector for x in test_doc]

clf_wv.predict(test_x)

array(['Books'], dtype='<U7')

# Regexes

### Regras de expressões regulares

https://cheatography.com/davechild/cheat-sheets/regular-expressions/

In [6]:
import re

regexp = re.compile(r"^ab[^\s]*cd")

phrases = ['abcd','xxx','abxxxcd','ab cd','aaaabxxcdccc']

match=[]
for phrase in phrases:
    if re.match(regexp,phrase):
        match.append(phrase)
        
print(match)    

['abcd', 'abxxxcd']


# Stemming / Lemmatization

In [11]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

#stemming can create problems with punctuation and some words
phrase =  "im loving to read the books! These stories are so cool"
words = word_tokenize(phrase)

stemmed_words = []
for word in words:
    stemmed_words.append(stemmer.stem(word))

" ".join(stemmed_words)

'im love to read the book ! these stori are so cool'

In [12]:
from nltk.stem import WordNetLemmatizer

lemma = WordNetLemmatizer()

#phrase = "eu estou adorando ler essas histórias, elas são muito boas"
phrase = "im loving to read the books! These stories are so cool"
words = word_tokenize(phrase)

lemma_words = []
for word in words:
    lemma_words.append(lemma.lemmatize(word, pos='v'))

" ".join(lemma_words)

'im love to read the book ! These stories be so cool'

# Stopwords removal

### Removing words that dont contain much meaning (the, this, that, he, it) 

In [13]:
from nltk.corpus import stopwords

stop = stopwords.words('english')

phrase = 'Here we have an exemple to show the removal of stop words!'
words = word_tokenize(phrase)

stripped_phrase = []
for word in words:
    if word not in stop:
        stripped_phrase.append(word)

new_phrase = [" ".join(stripped_phrase)]
print(new_phrase)

['Here exemple show removal stop words !']


# Textblob

### corrigir gramática

In [14]:
from textblob import TextBlob

phrase = "Thanks"
tb_phrase = TextBlob(phrase)

#corrigir
tb_phrase = tb_phrase.correct()
print(tb_phrase)

Thanks


In [18]:
#speech taging
tb_phrase.tags

#spacy.explain('NNS')

[('Thanks', 'NNS')]

In [19]:
#sentimento
tb_phrase.sentiment

Sentiment(polarity=0.2, subjectivity=0.2)